### ISSUE TITLE
File di dalam STATIC tidak bisa diload

### ISSUE THREAD

**Issue by fannyhasbi** [Harazaki/PHP-BOOTSTRAP#13]
File di dalam folder STATIC_ tidak bisa diload ketika menggunakan custom port. Perintah berikut akan menyalakan server di port 8000 dengan folder root-nya adalah PHP_BOOTSTRAP
   `php -S localhost:8000 -t PHP_BOOTSTRAP/`

Semua file yang mengarah ke file statis tidak akan bisa diload karena nomor port tidak terbaca. Di dalam file-nya akan menjadi:
**Perhatikan folder setelah localhost**
`<link href="http://localhost//STATIC/LIB/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>`

Namun ketika file PHP_BOOTSTRAP diletakkan di dalam folder htdocs semuanya normal. Berikut baris ketika load file statis-nya:
`<link href="http://localhost/PHP_BOOTSTRAP/STATIC/LIB/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>`

**Comment by septyaman** [comment]
Terima kasih penelitiannya. Sedang ditinjau
Good Work ! 👍

**Comment by fannyhasbi** [comment]
Fixed in #14
